export const {
	USER_API_BASE_URL = "http://localhost:3000/users",
	PRODUCT_API_BASE_URL = "http://localhost:3000/products",
	SOLACE_HOST = "ws://localhost:8008",
	SOLACE_VPN_NAME = "default",
	SOLACE_USERNAME = "frontend_user",
	SOLACE_PASSWORD = "password",
	SOLACE_TOPIC = "product/views",
} = import.meta.env;
